spring.application.name=aether-ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/aetherledger
spring.datasource.username=postgres
spring.datasource.password=AnMC_2a3_4-9ck2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true