-- ============================================================
-- AetherLedger — V1 baseline schema
-- ============================================================
--
-- Design notes
-- ─────────────────────────────────────────────────────────────
-- • TIMESTAMPTZ for every timestamp column.  UTC is stored and
--   retrieved without ambiguity regardless of server locale.
-- • NUMERIC(19, 4) for every monetary amount: 15 integer digits
--   and 4 decimal places, consistent with the domain entities.
-- • UUID primary keys are generated by the application layer
--   (GenerationType.UUID); no DB sequence or DEFAULT is needed.
-- • CHECK constraints duplicate enum guards already enforced by
--   the service layer, providing a second line of defence against
--   rogue writes that bypass the application.
-- • Every foreign key and index is named explicitly so that
--   future migrations can reference them without guessing the
--   name Hibernate would have auto-generated.
-- • ledger_entries and reconciliation_run_items are append-only;
--   no UPDATE paths exist for them in the application.
-- ============================================================


-- ============================================================
-- accounts
-- ============================================================
CREATE TABLE accounts (
    id         UUID         NOT NULL,
    name       VARCHAR(100) NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    version    BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_accounts
        PRIMARY KEY (id),

    CONSTRAINT uq_account_name
        UNIQUE (name),

    -- mirrors AccountType enum: USER, SYSTEM, MERCHANT
    CONSTRAINT chk_account_type
        CHECK (type IN ('USER', 'SYSTEM', 'MERCHANT'))
);

-- matches @Index(name = "idx_account_type", columnList = "type") on Account
CREATE INDEX idx_account_type ON accounts (type);


-- ============================================================
-- ledger_transactions
-- ============================================================
--
-- Self-referential foreign keys (reversal linkage) are added
-- via ALTER TABLE after the table is created.
-- ============================================================
CREATE TABLE ledger_transactions (
    id           UUID        NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    version      BIGINT       NOT NULL DEFAULT 0,

    -- ── reconciliation fields ────────────────────────────────
    -- Populated by an explicit reconcile() call; null until then.
    external_reference_id VARCHAR(255),
    external_status       VARCHAR(20),
    reconciled_at         TIMESTAMPTZ,

    -- ── PENDING intent fields ────────────────────────────────
    -- Captured at PENDING creation so complete() can post entries
    -- without the caller re-supplying them.  Null for transactions
    -- posted directly to SUCCESS via the immediate-post path.
    debit_account_id  UUID,
    credit_account_id UUID,
    amount            NUMERIC(19, 4),

    -- ── reversal linkage ─────────────────────────────────────
    -- reversal_of_transaction_id  : set on the reversal tx, points to original
    -- reversed_by_transaction_id  : set on the original tx, points to reversal;
    --                               UNIQUE prevents a transaction being reversed twice
    reversal_of_transaction_id UUID,
    reversed_by_transaction_id UUID,

    CONSTRAINT pk_ledger_transactions
        PRIMARY KEY (id),

    -- matches @Column(unique = true) on referenceId
    CONSTRAINT uq_tx_reference_id
        UNIQUE (reference_id),

    -- matches @Column(unique = true) on reversedByTransactionId;
    -- prevents two original transactions being reversed by the same reversal tx
    CONSTRAINT uq_tx_reversed_by
        UNIQUE (reversed_by_transaction_id),

    -- mirrors TransactionStatus enum: PENDING, SUCCESS, FAILED
    CONSTRAINT chk_tx_status
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),

    -- mirrors ExternalStatus enum: PENDING, SUCCESS, FAILED, NOT_FOUND
    CONSTRAINT chk_tx_external_status
        CHECK (external_status IN ('PENDING', 'SUCCESS', 'FAILED', 'NOT_FOUND')),

    -- intent field FKs — nullable; only populated on PENDING transactions
    CONSTRAINT fk_tx_debit_account
        FOREIGN KEY (debit_account_id) REFERENCES accounts (id),

    CONSTRAINT fk_tx_credit_account
        FOREIGN KEY (credit_account_id) REFERENCES accounts (id)
);

-- Self-referential FKs added after the table exists
ALTER TABLE ledger_transactions
    ADD CONSTRAINT fk_tx_reversal_of
        FOREIGN KEY (reversal_of_transaction_id)
        REFERENCES ledger_transactions (id);

ALTER TABLE ledger_transactions
    ADD CONSTRAINT fk_tx_reversed_by
        FOREIGN KEY (reversed_by_transaction_id)
        REFERENCES ledger_transactions (id);

-- matches @Index(name = "idx_ledger_transaction_reference_id", unique = true) on LedgerTransaction
-- The UNIQUE constraint above already enforces uniqueness; this named index
-- ensures the planner uses the canonical name from the entity annotation.
CREATE UNIQUE INDEX idx_ledger_transaction_reference_id
    ON ledger_transactions (reference_id);


-- ============================================================
-- ledger_entries
-- ============================================================
--
-- Immutable double-entry records.  No UPDATE paths exist.
-- Every transaction must produce exactly two entries whose
-- amounts sum to zero (enforced by the service layer; the
-- chk_entry_amount_nonzero constraint catches zero-amount rows).
-- ============================================================
CREATE TABLE ledger_entries (
    id                    UUID           NOT NULL,
    account_id            UUID           NOT NULL,
    ledger_transaction_id UUID           NOT NULL,
    amount                NUMERIC(19, 4) NOT NULL,
    created_at            TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pk_ledger_entries
        PRIMARY KEY (id),

    -- zero-amount entries are never valid (credit > 0, debit < 0)
    CONSTRAINT chk_entry_amount_nonzero
        CHECK (amount <> 0),

    -- matches @ForeignKey(name = "fk_ledger_entry_account") on LedgerEntry
    CONSTRAINT fk_ledger_entry_account
        FOREIGN KEY (account_id) REFERENCES accounts (id),

    -- matches @ForeignKey(name = "fk_ledger_entry_ledger_transaction") on LedgerEntry
    CONSTRAINT fk_ledger_entry_ledger_transaction
        FOREIGN KEY (ledger_transaction_id) REFERENCES ledger_transactions (id)
);

-- matches @Index(name = "idx_ledger_entry_account_id") on LedgerEntry
CREATE INDEX idx_ledger_entry_account_id
    ON ledger_entries (account_id);

-- matches @Index(name = "idx_ledger_entry_ledger_transaction_id") on LedgerEntry
CREATE INDEX idx_ledger_entry_ledger_transaction_id
    ON ledger_entries (ledger_transaction_id);


-- ============================================================
-- reconciliation_runs
-- ============================================================
--
-- Immutable audit record written once when a batch
-- reconciliation completes.  All count columns are totals
-- captured at run time and never recalculated.
-- ============================================================
CREATE TABLE reconciliation_runs (
    id                               UUID        NOT NULL,
    created_at                       TIMESTAMPTZ NOT NULL,
    total_items                      INT         NOT NULL,
    updated_count                    INT         NOT NULL,
    matched_count                    INT         NOT NULL,
    mismatch_count                   INT         NOT NULL,
    missing_transaction_count        INT         NOT NULL,
    missing_external_reference_count INT         NOT NULL,

    CONSTRAINT pk_reconciliation_runs
        PRIMARY KEY (id),

    CONSTRAINT chk_run_total_items_nonneg
        CHECK (total_items >= 0),
    CONSTRAINT chk_run_updated_count_nonneg
        CHECK (updated_count >= 0),
    CONSTRAINT chk_run_matched_count_nonneg
        CHECK (matched_count >= 0),
    CONSTRAINT chk_run_mismatch_count_nonneg
        CHECK (mismatch_count >= 0),
    CONSTRAINT chk_run_missing_tx_count_nonneg
        CHECK (missing_transaction_count >= 0),
    CONSTRAINT chk_run_missing_ref_count_nonneg
        CHECK (missing_external_reference_count >= 0)
);


-- ============================================================
-- reconciliation_run_items
-- ============================================================
--
-- Per-item trace within a reconciliation run.  Immutable.
-- transaction_id is null when no internal transaction matched
-- the provider's referenceId (item_status = 'NOT_FOUND').
-- ============================================================
CREATE TABLE reconciliation_run_items (
    id                    UUID         NOT NULL,
    reconciliation_run_id UUID         NOT NULL,
    reference_id          VARCHAR(255) NOT NULL,
    transaction_id        UUID,
    reconciliation_result VARCHAR(40),
    item_status           VARCHAR(20)  NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_reconciliation_run_items
        PRIMARY KEY (id),

    -- mirrors the two outcomes BatchReconcileItemResult can produce
    CONSTRAINT chk_recon_item_status
        CHECK (item_status IN ('UPDATED', 'NOT_FOUND')),

    -- mirrors ReconciliationResult enum values stored as strings
    CONSTRAINT chk_recon_item_result
        CHECK (reconciliation_result IN (
            'NOT_RECONCILED',
            'MISSING_EXTERNAL_REFERENCE',
            'MATCHED',
            'STATUS_MISMATCH'
        )),

    -- matches @ForeignKey(name = "fk_recon_run_item_run") on ReconciliationRunItem
    CONSTRAINT fk_recon_run_item_run
        FOREIGN KEY (reconciliation_run_id) REFERENCES reconciliation_runs (id),

    -- nullable FK: null when item_status = 'NOT_FOUND'
    CONSTRAINT fk_recon_run_item_tx
        FOREIGN KEY (transaction_id) REFERENCES ledger_transactions (id)
);

-- matches @Index(name = "idx_recon_run_item_run_id") on ReconciliationRunItem
CREATE INDEX idx_recon_run_item_run_id
    ON reconciliation_run_items (reconciliation_run_id);
